### ISSUE TITLE
libnacos-cli.a(HTTPCli.o): undefined reference to symbol 'curl_easy_cleanup@@CURL_GNUTLS_3'

### ISSUE THREAD

**Issue by geiliwanghaichao** [nacos-group/nacos-sdk-cpp#105]
使用nacos-sdk-cpp-1.0.7 tag编译出来的静态库，放在应用程序中后，编译应用程序，有如下报错：
/usr/bin/ld: ../common/lib/libnacos-cli.a(HTTPCli.o): undefined reference to symbol 'curl_easy_cleanup@@CURL_GNUTLS_3'
//usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4: error adding symbols: DSO missing from command line

注：gcc版本为：7.5.0，系统为Ubuntu16.04.7
不知道什么原因，劳烦大神帮解

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
@geiliwanghaichao 
麻烦在程序中增加-lcurl试试看行吗？
