### ISSUE TITLE
源码使用了rapidjson一个较老的版本，如果自己的程序里引用了rapidjson导致版本冲突

### ISSUE THREAD

**Issue by yanghxstone** [nacos-group/nacos-sdk-cpp#119]

**Comment by xiedeacc** [comment]
+1 会导致core

**Comment by yanghxstone** [comment]
可以把自己要用的rapidjson库的命名空间改一下
// rename latest rapidjson namespace
#define RAPIDJSON_NAMESPACE rapidjson_latest

业务逻辑里使用rapidjson_latest 作为rapidjson库的命名空间来用

**Comment by xiedeacc** [comment]
我自己把这个sdk的rapidjson完全删掉，就可以了
