### ISSUE TITLE
Beatreactor heartbeat mechanism optimization is needed/Beatreactor的心跳机制需要优化

### ISSUE THREAD

**Issue by TTTTTAAAAAKKKKEEEENNNN** [nacos-group/nacos-sdk-cpp#20]
Currently, the beatreactor will periodically check the beatinfo list (every 5 secs.)
and send beat for each beatinfo, so there will be multiple requests in a short time, which will be problematic(heavy network access in a short time).
The following mechanism is proposed and will be implemented in coming version:

For each beatinfo, there will be a variable to keep the next time when the heartbeat should be send (next_hb_time)
the addBeatInfo() function will initialize it with the initial value(the time when addBeatInfo() is called)
after the beatinfo is added to the list, call sort() on the list with ascending order (next_hb_time as the sorting key)
the heartbeat worker will:
1. Check all the due items and send heartbeat
2. Update the next_hb_time for them(next_hb_time + HB_INTERVAL)
3. Sort the list until there's no due item
4. Find the first item and sleep for (item.next_hb_time - now()) seconds

this will make heartbeat requests not concentrated on a particular time, thus improving the performance of both client side and server side

当前的beatreactor会周期性的（每5秒）检查beatinfo并且一次性全部发出，这会引发问题（短时间内发生大量网络访问）
对这个问题，提出了下面的解决方案并且会在后续的版本中进行实现：

对于每个beatinfo，将会记录其下次应该发送心跳的时间(next_hb_time)
addBeatInfo() 函数将会初始化这个值(当调用addBeatInfo()时将会设置它)
当这个beatinfo被放到心跳信息列表时,通过sort()对这个列表进行升序排列(next_hb_time作为排序键)
heartbeat工作线程将会执行下述操作:
1. 检查所有超时的项并且发送心跳
2. 更新他们的next_hb_time(next_hb_time + HB_INTERVAL)
3. 对列表进行排序，直到没有超时的项目
4. 找到列表的第一项，并且睡眠(item.next_hb_time - now())秒

这样心跳就不会集中在一个时刻发出，这可以改善客户端和服务端的网络性能

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
在master上修复了

fixed in master branch

**Comment by hjx777** [comment]
请问注册一个临时实例自动带有心跳，但是在注册中心还是无法长时间存在，后续会变成不健康模式并被删除，这个是因为心跳机制没有起作用吗？
