### ISSUE TITLE
An elegant String solution is needed/需要一个更优雅的String实现

### ISSUE THREAD

**Issue by TTTTTAAAAAKKKKEEEENNNN** [nacos-group/nacos-sdk-cpp#23]
Currently, we are using NacosString as the alias of std::string in this project, but it's problematic.
We expect a string solution that can:
1. notate null string (equivalent to String s = null in java)
2. support encoding option
3. the null status can be assigned from one string to another
4. compare between null string and a normal string can be performed and will get false

This solution doesn't necessarily need to be a string implementation, a solution to replace the existing NacosString schema is welcome

当前系统中，NacosString其实只是std::string的一个别名，但是这会在后续开发中引发问题。
我们需要一个string解决方案，能够：
1. 表示null字符串（相当于java中的String s = null）
2. 支持不同的编码
3. 将null对象从一个string传递到另外一个
4. null字符串和非null字符串可以进行比较而且会返回false

这并不一定是要一个实现，也可以是一个解决方案替换掉现在的NacosString方案

**Comment by yzz-ihep** [comment]
For the second item,i think,a string util is good enough.

**Comment by yzz-ihep** [comment]
"std::string*"fits other descriptions

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
@yzz-ihep Actually that parameter doesn't work
That is the feature needs to be added

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
当前没有更好的处理办法，暂且使用系统的string

As we don't have a better solution for string, we use std::string
