### ISSUE TITLE
When the namespace is 'public', cpp SDK will not be able to add listener normally.

### ISSUE THREAD

**Issue by zu1y** [nacos-group/nacos-sdk-cpp#26]
run `test/testcase/testListenWorker.cpp`

Whether the configuration has changed or not , It's going to make requests all the time and server will return all config values.

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
Could you show me the screen shot of the output?
maybe you have seen the testcase getting other configurations, because the testcase is:
...
    thelistener->setKey("k");
    bool bSucc;
    try {
        NacosServiceFactory *factory = new NacosServiceFactory(props);
        ResourceGuard <NacosServiceFactory> _guardFactory(factory);
        ConfigService *n = factory->CreateConfigService();
        ResourceGuard <ConfigService> _serviceFactory(n);
        n->addListener("k4", NULLSTR, thelistener);
        n->addListener("k2", NULLSTR, thelistener);
        n->addListener("k", NULLSTR, thelistener);
        bSucc = n->publishConfig("k", NULLSTR, "hahaha");
        cout << "Input a character to continue" << endl;
... 

Actually it's watching 3 keys but only 1 key is created.
And the polling function will periodically (every 30 secs.) send a request to get the keys being watched from the server, which could be the pull request you described in your comment
Furthermore, the debug level is set to DEBUG by default so you can see verbose output, you can turn it to ERROR to see less message.

**Comment by zu1y** [comment]
@TTTTTAAAAAKKKKEEEENNNN 
hi, it my test code and output.

My config in `public` namespace.

when i don't set `props[PropertyKeyConst::NAMESPACE]`, run testcase and update config value. the output is ok

the code: 

```cpp
#include <stdlib.h>
#include <stdio.h>
#include <iostream>
#include "factory/NacosServiceFactory.h"
#include "listen/Listener.h"
#include "PropertyKeyConst.h"
#include "ResourceGuard.h"
#include <ctime>

class KeyChangeListener : public Listener {
private:
    NacosString key;
public:
    void setKey(const NacosString &_key) { key = _key; };

    NacosString getKey() const { return key; };

    void receiveConfigInfo(const NacosString &configInfo) {
        time_t now = time(0);
        std::cout << "time:" << now <<  "  in receiveConfigInfo: " << key << " changed to " << configInfo << std::endl;
    }
};

int main() {
    Properties props;
    props[PropertyKeyConst::SERVER_ADDR] = "127.0.0.1:8848";
    // props[PropertyKeyConst::NAMESPACE] = "public";
    NacosServiceFactory *factory = new NacosServiceFactory(props);
    ResourceGuard<NacosServiceFactory> _guardFactory(factory);
    ConfigService *n = factory->CreateConfigService();
    ResourceGuard<ConfigService> _serviceFactory(n);

    std::cout << "test listener" << std::endl;
    KeyChangeListener *thelistener = new KeyChangeListener();
    thelistener->setKey("test");
    bool bSucc;
    try {
        n->addListener("test", "test", thelistener);
    }
    catch (NacosException e) {
        std::cout <<
                  "Failed to add listener" << std::endl <<
                  "Reason:" << e.what() << std::endl;
        return false;
    }
    std::cout << "Input a character to continue" << std::endl;
    getchar();
    return 0;
}
```

the output :
```
test listener
Input a character to continue
res test%02test%01
time:1601448943  in receiveConfigInfo: test changed to testkey=value
```
that's all, until next time i update config value..


use the same code, but open namespace config `props[PropertyKeyConst::NAMESPACE] = "public"`,  and i don't update the config value, the output is out of control.

The output 
```
test listener
Input a character to continue
res test%02test%02public%01
time:1601449074  in receiveConfigInfo: test changed to testkey=value
res test%02test%02public%01
time:1601449075  in receiveConfigInfo: test changed to testkey=value
res test%02test%02public%01
time:1601449077  in receiveConfigInfo: test changed to testkey=value
res test%02test%02public%01
time:1601449078  in receiveConfigInfo: test changed to testkey=value
res test%02test%02public%01
time:1601449079  in receiveConfigInfo: test changed to testkey=value
res test%02test%02public%01
```

plz look at the timestamp, print config every second.

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
Could you try this branch to see if the bug is fixed?
https://github.com/nacos-group/nacos-sdk-cpp/tree/bugfixIssue%2326

Please use 'Public' instead of 'public' for the namespace, because actually you can create a space named 'public' in nacos, and it is not considered as the default public namespace

Actually, namespace 'Public' = request with namespace parameter=empty
So I added snippet to set namespace parameter empty when it's public.

**Comment by zu1y** [comment]
@TTTTTAAAAAKKKKEEEENNNN 

use 'Public', the problem is solved

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
Thank you ! I'll merge it into master.
