### ISSUE TITLE
Case issues in the project's directories

### ISSUE THREAD

**Issue by TTTTTAAAAAKKKKEEEENNNN** [nacos-group/nacos-sdk-cpp#3]
I think it would be better to use lower case directory names in the project, e.g.:
nacos-sdk-cpp/src/config/core/
instead of:
nacos-sdk-cpp/src/config/Core/

and so on

what is your opinion?
@yanlinly @chaytanyasinha

**Comment by chaytanyasinha** [comment]
@TTTTTAAAAAKKKKEEEENNNN yes,we can do the changes as the project is now just merged to the development branch and after proper discussion between us it will be merged to the master branch. 
Thanks for your kind suggestions.

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
Solved.
1. the source directories within the project will all be lower case
2. source files will be, too
