### ISSUE TITLE
window10 system compilation error, syscall.h not found

### ISSUE THREAD

**Issue by lidaoyang** [nacos-group/nacos-sdk-cpp#34]
![image](https://user-images.githubusercontent.com/26211950/96815432-aa799a00-144f-11eb-91f3-cfa3a976f2ab.png)

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
Could you advise the compiler/environment? (e.g.: gcc + cygwin, etc.)

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
Hi @lidaoyang ,

Could you try this version:
https://github.com/nacos-group/nacos-sdk-cpp/tree/develop

to see if the issue is resolved?
Thanks.
