### ISSUE TITLE
failed to request https nacos server throwing error/无法请求https nacos服务器，抛出异常

### ISSUE THREAD

**Issue by doingsimple** [nacos-group/nacos-sdk-cpp#39]
For example:
https://example.com:8848

bug happend here:
![image](https://user-images.githubusercontent.com/58580567/98318804-514a6280-201a-11eb-8deb-b133b4e4ad5e.png)

例如：
https://example.com:8848

bug发生在这里:
![image](https://user-images.githubusercontent.com/58580567/98318804-514a6280-201a-11eb-8deb-b133b4e4ad5e.png)

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
Thank you for your issue.

This actually involves 2 items:
1. Address parse bug: need to parse http/https prefix and [:port] suffix
2. HTTPS support

for item 1, I think it's easy to solve, I will solve it immediately.
for item 2, HTTPS support for libcurl is needed, and I will be working on it.

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
Hi @doingsimple ,
Could you try this and see if the issue is solved?
https://github.com/nacos-group/nacos-sdk-cpp/tree/develop

I've verified that item 1 is solved.
For item 2, I don't have a https server, but I think it should be solved since I tried to access https servers (e.g.: https://www.baidu.com) with HTTPCli and succeed in getting response.

**Comment by doingsimple** [comment]
Thanks. I'm afraid that there's still a little problem on FUNCTION NamingProxy.cpp:callServer,LINE:171

NacosString NamingProxy::callServer

(

const NacosString &api,

list <NacosString> &params,

const NacosString &curServer,

int method

) throw(NacosException) {

NacosString requestUrl;

//Current server address doesn't have SERVER_ADDR_IP_SPLITER, which means

if (!ParamUtils::contains(curServer, UtilAndComs::SERVER_ADDR_IP_SPLITER)) {

requestUrl = curServer + UtilAndComs::SERVER_ADDR_IP_SPLITER + serverPort;

} else {

requestUrl = curServer;

}


//TODO:http/https implementation

requestUrl = "http://" + requestUrl + api; (HERE...!!!)


HttpResult requestRes;

list <NacosString> headers;

headers = builderHeaders();


Have a nice day.

________________________________
发件人: HakureiGenei <notifications@github.com>
发送时间: 2020年11月8日 0:19
收件人: nacos-group/nacos-sdk-cpp <nacos-sdk-cpp@noreply.github.com>
抄送: doingsimple <doingsimple@hotmail.com>; Mention <mention@noreply.github.com>
主题: Re: [nacos-group/nacos-sdk-cpp] failed to request https nacos server throwing error (#39)


Closed #39<https://github.com/nacos-group/nacos-sdk-cpp/issues/39>.

―

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
I found that I've missed many test items(for http prefix) in my testcases, I'll add them and go through all test cases and come back to you, thanks!

我发现我可能在测试案例中漏掉了很多测试项目(给http前缀的)，我会全部加上并且测试完毕再反馈你，谢谢！
