### ISSUE TITLE
Crash on building heart beat json package/创建json心跳包时程序崩溃

### ISSUE THREAD

**Issue by doingsimple** [nacos-group/nacos-sdk-cpp#40]
Hi. I'm using the nacos-sdk-cpp in my project. 
It's easy to crash after registerInstance with heartbeat when service has been running for a while:

JSON.CPP:
![image](https://user-images.githubusercontent.com/58580567/98493501-90282480-2275-11eb-8d13-a3200c4e3f52.png)

I tried to pass Document parameter to Map2JSONObject, the crash doesn't happen any more as far now.

void JSON::Map2JSONObject(Value &jsonOb, map <NacosString, NacosString> &mapinfo) 
==>
void JSON::Map2JSONObject(rapidjson::Document& d, Value& jsonOb, map <NacosString, NacosString>& mapinfo) 

你好，我在我的工程中使用了nacos-sdk-cpp.
当我调用registerInstance之后一段时间，程序很容易崩溃：

JSON.CPP:
![image](https://user-images.githubusercontent.com/58580567/98493501-90282480-2275-11eb-8d13-a3200c4e3f52.png)

我尝试将document参数传给Map2JSONObject， 到目前为止，程序不再崩溃。

void JSON::Map2JSONObject(Value &jsonOb, map <NacosString, NacosString> &mapinfo) 
==>
void JSON::Map2JSONObject(rapidjson::Document& d, Value& jsonOb, map <NacosString, NacosString>& mapinfo)

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
I think your solution is correct,
I don't know why I didn't pass the document parameter to the function :(
Could you try the development branch to see if the issue is solved?

**Comment by doingsimple** [comment]
Thanks! I'll try it as soon as possible.

**Comment by doingsimple** [comment]
it works now.
