### ISSUE TITLE
naming/NamingProxy.h    non-existen      how to deal with it   ,think

### ISSUE THREAD

**Issue by zhang5207892** [nacos-group/nacos-sdk-cpp#41]
naming/NamingProxy.h    non-existen      how to deal with it   ,think

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
Hi @zhang5207892 ,

Could you provide more information (e.g.: screenshot, log, etc.) for this issue? thanks!

你好 @zhang5207892 ，
请问你能提供更多详细的信息吗（例如截图，日志等），谢谢！

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
没有收到你的回应，我将要关闭此issue

I'm closing this issue because I didn't receive any response from you
