### ISSUE TITLE
没有使用的临时对象objectConfigData

### ISSUE THREAD

**Issue by wensheng-zhang** [nacos-group/nacos-sdk-cpp#43]
在NacosServiceFactory.cpp中CreateNamingService/CreateConfigService/CreateNamingMaintainService中都创建了objectConfigData临时对象，并对其成员进行了复制，但是该对象没有被使用。请确认。

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
你好 wensheng-zhang，
这个对象在master分支中确实没有用到，它是一个栈对象，函数退出后会被正常析构掉，而真正的NacosService会在相应的析构函数中进行析构。
实际上这个是析构代理，你可以看develop分支当中，这个对象被建立在堆上面，而且NacosService的析构过程被重构到这个对象当中了。
