### ISSUE TITLE
### 订阅和取消订阅服务  这个功能是否真的做好了呀？/ Is Service subscription/unsubscription feature completed

### ISSUE THREAD

**Issue by lyj2871** [nacos-group/nacos-sdk-cpp#44]
#include <iostream>
#include <stdlib.h>
#include <unistd.h>
#include "factory/NacosServiceFactory.h"
#include "ResourceGuard.h"
#include "naming/subscribe/EventListener.h"
#include "PropertyKeyConst.h"
#include "DebugAssertion.h"
#include "Debug.h"

using namespace std;
using namespace nacos;

class MyServiceListener : public EventListener {
private:
    int num;
public:
    MyServiceListener(int num) {
        this->num = num;
    }

    void receiveNamingInfo(const ServiceInfo &serviceInfo){
        cout << "===================================" << endl;
        cout << "Watcher: " << num << endl;
        cout << "Watched service UPDATED: " << serviceInfo.toInstanceString() << endl;
        cout << "===================================" << endl;

    }
};

int main() {
    Properties props;
    props[PropertyKeyConst::SERVER_ADDR] = "127.0.0.1:8848";
    //Interval for poller to check the status of subscribed services(unit:Ms), 30000 by default
    //Here we set it to 5000 to see the output more quick
    props[PropertyKeyConst::TCP_NAMING_POLL_INTERVAL] = "5000";
    NacosServiceFactory *factory = new NacosServiceFactory(props);
    ResourceGuard <NacosServiceFactory> _guardFactory(factory);
    NamingService *n = factory->CreateNamingService();
    ResourceGuard <NamingService> _serviceFactory(n);

    n->subscribe("ss", new MyServiceListener(1));
    cout << "Press any key to register services" << endl;
    getchar();

    n->registerInstance("ss", "127.0.0.1", 33);
    n->registerInstance("ss", "127.0.0.1", 34);
    cout << "Press any key to deregister services" << endl;
    getchar();

    n->deregisterInstance("ss", "127.0.0.1", 33);
    n->deregisterInstance("ss", "127.0.0.1", 34);
    cout << "All instances Unregistered, press any key to finish testing" << endl;
    getchar();

    return 0;
}

这是源码提供的测试实例。    这里面的注册服务没有任何问题，注册后，nacos 控制台上也能看到注册的实例 ，但是订阅貌似不起作用呀，订阅后，nacos 控制台上，订阅者列表里面也搜索不到订阅者， receiveNamingInfo  这个函数也没有被调用过。

代码是否经过测试呀？

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
你好 ljy2871，
这个功能是已经完成并且有测试过的，只不过实现方式和Java的客户端有点不同。
我这边的订阅实际上是通过TcpNamingServicePoller轮询来实现的，当发现服务变化后，通过EventDispatcher的notifyDirectly直接在本线程发送给监听者
关于第二点，订阅者列表中找不到订阅者，这个这个问题我将继续确认，如果是有问题，我会进行修复

**Comment by wensheng-zhang** [comment]
你好，TTTTTAAAAAKKKKEEEENNNN
很抱歉地问一下，不知道这个issue OK了吗。
今天我也跑了测试单例：testListenService，发现设置的listener并没有被调用。后来，在注册实例之后，通过maintainService对实例进行了修改，listener的回调函数同样也没有被调用。
我对subscribe函数的理解：service中的实例发生了修改，应该会调用listener的回调函数，不知道为什么没有被调用。
麻烦帮忙给确认一下。

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
@wensheng-zhang 我知道你们遇到的是什么问题了：
请把配置的PropertyKeyConst::TCP_NAMING_POLL_INTERVAL这个参数调短一点，因为我们的监听和java实现不一样：我们使用的是轮询法检测变更，这个参数默认值是30秒，可能比较长，设置成10 或者5就可以解决这个问题，但是可能引发频繁查询服务器的问题，java客户端的那种监听我也会在后面的版本实现

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
你好 @lyj2871 @wensheng-zhang 经过和java客户端的比较，发现这一段确实有问题：没有正确调用接口，在服务器的订阅者列表中看不到订阅信息，目前正在修复当中。

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
你好 @lyj2871 @wensheng-zhang，
目前这个功能已经完成，并且现在能够在订阅者的列表出现客户端。
目前代码还在开发分支，预计最近会发一个版本。
