### ISSUE TITLE
按README.md中“将libnacos-cli集成到你的工程“章节编译报错

### ISSUE THREAD

**Issue by cuizhipeng326** [nacos-group/nacos-sdk-cpp#49]
按README.md中“将libnacos-cli集成到你的工程“章节编译报错，具体是执行文档中的命令`g++ IntegratingIntoYourProject.cpp -L. -lnacos-cli -Iinclude -o integrated.out`时报错，如下：
In file included from include/naming/subscribe//EventListener.h:11:0,
                 from include/naming/NamingService.h:7,
                 from include/factory/INacosServiceFactory.h:8,
                 from include/factory/NacosServiceFactory.h:8,
                 from register_nacos.cpp:4:
include/DebugAssertion.h:7:10: 致命错误：src/log/Logger.h：没有那个文件或目录
 #include "src/log/Logger.h"
          ^~~~~~~~~~~~~~~~~~

两个问题：
1.`include/naming/subscribe//EventListener.h`应该为`include/naming/subscribe/EventListener.h`，多了一个`/`
2.找不到`src/log/Logger.h`是因为编译命令中没有`-I.`，自然找不到src目录下的文件，另外，为什么include里面的头文件包含src目录下的头文件，是不是把src里的Logger.h放在include里更合适

看到的兄弟看能不能优化下

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
麻烦能提供下编译环境和编译器版本吗，我要朝霞这个问题的原因，还有，我可能会把DebugAssertion这个移动到src目录下，因为这个不需要对外开放

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
关于第二个问题：现在这个问题在develop分支已经修复，预计后续会发一个版本，如果你急着用，可以先用develop分支
关于第一个问题：估计是makefile有问题，后续会处理它的，但是现在不影响编译，麻烦忽略它

**Comment by cuizhipeng326** [comment]
> 关于第二个问题：现在这个问题在develop分支已经修复，预计后续会发一个版本，如果你急着用，可以先用develop分支
> 关于第一个问题：估计是makefile有问题，后续会处理它的，但是现在不影响编译，麻烦忽略它

优化了就行
