### ISSUE TITLE
将nacos-sdk-cpp编译成so集成到自己项目中时报错 / Exception when integrating SO file into my own project

### ISSUE THREAD

**Issue by cuizhipeng326** [nacos-group/nacos-sdk-cpp#50]
nacos-sdk-cpp v1.0.4版本，解压后再在linux环境下，用gcc7.4.0，cmake2.8.12.2直接make，没有报错，生成nacos-cli成功，然后按照README.md里的指导将nacos-cli集成到自己的项目中，简单写了一个cpp和.h调用nacos sdk接口去nacos上注册和去注册，最后编译时候报错：
thirdparties/base/basetype.h:12:15: 错误：expected unqualified-id before numeric constant
  #define TRUE 1
thirdparties/nacos_wrapper/include/NacosString.h:21:30: 附注：in expansion of macro ‘TRUE’
     static const NacosString TRUE;
                              ^~~~
thirdparties/base/basetype.h:16:16: 错误：expected unqualified-id before numeric constant
  #define FALSE 0
                ^
thirdparties/nacos_wrapper/include/NacosString.h:22:30: 附注：in expansion of macro ‘FALSE’
     static const NacosString FALSE;
                              ^~~~~
这个错误应该是nacos sdk中的静态变量和另外一个三方库的宏同名冲突了

另一个报错是：
thirdparties/nacos_wrapper/src/thread/Mutex.h:19:5: 错误：‘TID_T’不是一个类型名
     TID_T _holder;
     ^~~~~
thirdparties/nacos_wrapper/src/thread/Mutex.h: 在成员函数‘void nacos::Mutex::assignHolder()’中:
thirdparties/nacos_wrapper/src/thread/Mutex.h:38:27: 错误：‘_holder’在此作用域中尚未声明
     void assignHolder() { _holder = gettidv1(); };
                           ^~~~~~~
thirdparties/nacos_wrapper/src/thread/Mutex.h:38:27: 附注：suggested alternative: ‘_tolower’
     void assignHolder() { _holder = gettidv1(); };
                           ^~~~~~~
                           _tolower
thirdparties/nacos_wrapper/src/thread/Mutex.h:38:37: 错误：‘gettidv1’在此作用域中尚未声明
     void assignHolder() { _holder = gettidv1(); };
                                     ^~~~~~~~
thirdparties/nacos_wrapper/src/thread/Mutex.h:38:37: 附注：suggested alternative: ‘getgid’
     void assignHolder() { _holder = gettidv1(); };
                                     ^~~~~~~~
                                     getgid
thirdparties/nacos_wrapper/src/thread/Mutex.h: 在成员函数‘void nacos::Mutex::unassignHolder(’中:
thirdparties/nacos_wrapper/src/thread/Mutex.h:40:29: 错误：‘_holder’在此作用域中尚未声明
     void unassignHolder() { _holder = 0; };
                             ^~~~~~~
thirdparties/nacos_wrapper/src/thread/Mutex.h:40:29: 附注：suggested alternative: ‘_tolower’
     void unassignHolder() { _holder = 0; };
                             ^~~~~~~
                             _tolower
为啥找不到TID_T这个类型呢，看Tid.h源码：
`//for linux
#include <sys/syscall.h>
#include <unistd.h>
#define TID_T pid_t
#define gettidv1() syscall(__NR_gettid)`
limux下应该就是pid_t哇，单独make nacos sdk是可以生成libnacos-cli.so的，有人碰到过这种问题吗

**Comment by cuizhipeng326** [comment]
第一个问题：要么修改basetype.h中TRUE和FALSE的宏定义，要么修改NacosString.h中的TRUE和FALSE静态变量，因为有nacos sdk的源码，最后修改NacosString.h中的TRUE和FALSE为NAOCSTRUE和NACOSFALSE解决；
第二个问题：最后发现是Tid.h
`#ifndef __TID_HELPER_H_
#define __TID_HELPER_H_
#if defined(__CYGWIN__) || defined(MS_WINDOWS)
//TODO:for windows/cygwin
#include <sys/syscall.h>
#include <unistd.h>
#define TID_T pid_t
#define gettidv1() syscall(__NR_gettid)

#elif defined(linux)
//for linux
#include <sys/syscall.h>
#include <unistd.h>
#define TID_T unsigned long long
#define gettidv1() syscall(__NR_gettid)
//#define gettidv2() syscall(SYS_gettid)

#elif defined(__APPLE__) && defined(__MACH__)
//Mac OS code goes here
#define TID_T unsigned long long
TID_T gettidv1();

#endif//OS-specific code

#endif//HEADER_GUARD`
中的多个编译宏都匹配不上导致的，刚好里面也没有`#else`分支，所以最后就没有定义`TID_T`和`gettidv1`，而自己的项目里的cmake文件里定义的是`_LINUX_`，所以修改的话要么cmake中增加定义`linux`以适配nacos sdk的Tid.h，要么修改nacos sdk的Tid.h，将`#elif defined(linux)`改为`#elif defined(linux) || defined(_LINUX_)`来适配自己的项目

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
第一个问题确定是代码的问题，我会进行修改
第二个请问下你是用的什么编译器和环境，我想改下项目，适配你的情况 对于你说的这个情况，即：defined(LINUX)，我也会进行适配

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
关于这个TID的问题，我已经在TID.h里面对LINUX也做了兼容，不过我还是想等你提供下环境信息，以便于我做进一步的兼容处理，所以这个issue我暂时先不关闭

**Comment by cuizhipeng326** [comment]
> 关于这个TID的问题，我已经在TID.h里面对LINUX也做了兼容，不过我还是想等你提供下环境信息，以便于我做进一步的兼容处理，所以这个issue我暂时先不关闭

CentOS Linux release 7.6.1810 (Core)
gcc (GCC) 7.4.0
cmake version 2.8.12.2
TID_T的问题跟cmake工程的宏有关吧，各个工程怎么定义linux宏可能都不太一样，Tid.h中的编译宏里多枚举几种大家常用的linux的宏试试吧，或者加个#else分支做个统一处理？感觉也不太合适

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
我看了下，目前的解决方法是在linux这个分支的宏里面再兼容个defined(LINUX)，然后我也添加了#else分支，在这个分支我认为用户是使用的unix-like系统，后面如果还有不兼容的，再增加elif分支，目前这是最好的办法了。
