### ISSUE TITLE
当客户端服务启动后，并在监听配置时，如果关闭nacos服务。 客户端程序会崩溃

### ISSUE THREAD

**Issue by wanghyu** [nacos-group/nacos-sdk-cpp#52]

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
我在本地测试的时候是会以很高的频率重试，我现在修改了，在服务关闭的时候我间隔几秒再重试。
能描述下是怎么崩溃的吗？我没看到崩溃的问题，是指的coredump吗？

**Comment by wanghyu** [comment]
![image](https://user-images.githubusercontent.com/10007200/105932725-4d156a80-6088-11eb-8fd1-a1ad4e9fa0b9.png)

就是用的你监听配置的demo跑的，nacos服务正常的时候，监听确实都是ok的，但是，如果我吧nacos服务停掉，客户端进程就是段错误，然后core掉。

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
这个问题已经确认，后续将会修复，谢谢你的提出！

**Comment by wanghyu** [comment]
> 这个问题已经确认，后续将会修复，谢谢你的提出！

感谢作者的贡献～

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
已经修复了，麻烦看下develop分支的代码还有这个问题吗？

**Comment by wanghyu** [comment]
> 已经修复了，麻烦看下develop分支的代码还有这个问题吗？

已确认， 该问题已经修复了。
