### ISSUE TITLE
关于getConfig(const NacosString &dataId, const NacosString &group, long timeoutMs) throw(NacosException) = 0;

### ISSUE THREAD

**Issue by lekce** [nacos-group/nacos-sdk-cpp#55]
您好，getConfig方法内部实现中关于命名空间ID有个疑惑，为什么不把命名空间ID的参数开放出来：
   return getConfigInner(getNamespace(), dataId, group, timeoutMs);

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
你好 lekce, 这是因为namespace是在ConfigService或者NamingService初始化后就配置好的，一般不需要手工指定。
具体可以参考：
https://nacos.io/zh-cn/docs/architecture.html
数据模型这一章

如果你要指定别的名称空间，可以通过
appConfig[PropertyKeyConst::NAMESPACE] = "namespace-id";
或者在properties文件中添加：
namespace=namespace-id
来实现这个功能
