### ISSUE TITLE
arm64 build error: unknown mnemonic `lock' -- `lock xaddl x0,[x2]'

### ISSUE THREAD

**Issue by Xiongyou-Peng** [nacos-group/nacos-sdk-cpp#57]
Compiling error occurred when we build the nacos-sdk-cpp on arm64:
/tmp/ccbrPsXn.s: Assembler messages:
/tmp/ccbrPsXn.s:875: Error: unknown mnemonic `lock' -- `lock xaddl x0,[x2]'
Makefile:42: recipe for target '/home/megaium/nacos-sdk-cpp/obj/EventDispatcher.o' failed
make: *** [/home/megaium/nacos-sdk-cpp/obj/EventDispatcher.o] Error 1

How can I solve this problem?

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
Could you please provide the platform information and compiler/os information to solve this?

This error is due to that a x86-specific instruction is used to implement the atomic int operation, we need addition information to adapt it to ARM hardware

**Comment by Xiongyou-Peng** [comment]
The platform and compiler/os information as follows:
Linux version 5.4.0-47-generic (buildd@bos02-arm64-073) (gcc version 7.5.0 (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04)) #51~18.04.1-Ubuntu SMP Sat Sep 5 14:36:25 UTC 2020

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
Hi @Xiongyou-Peng ,

Could you try this:
https://github.com/nacos-group/nacos-sdk-cpp/tree/develop-atomics-no-asm

to see if the problem is solved?
The solution is to replace the inline asm atomic operation with the gcc built-in one.

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
If the problem still persists, please reopen this issue :)
