### ISSUE TITLE
CreateConfigService不想使用nacos-cpp-cli.properties 文件

### ISSUE THREAD

**Issue by worldup** [nacos-group/nacos-sdk-cpp#58]
NacosServiceFactory.cpp 
ConfigService *NacosServiceFactory::CreateConfigService() throw(NacosException) {
    Init::doInit();
     |
     |---> Logger::Init();
                 |
                 |--->Logger::initializeLogSystem()    line 152 **ConfigParserUtils::parseConfigFile**
   为什么必须从nacos-cpp-cli.properties 加载log的配置，如果调用的是NacosServiceFactory(props)本来就是想从properties中传递参数，而不是从nacos-cpp-cli.properties里面，这样一搞项目里面没有nacos-cpp-cli.properties 文件系统就crash了.所以建议在Logger::initializeLogSystem()  中对ConfigParserUtils::parseConfigFile 加个catch .

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
这里我还需要想一下具体的解决方法，因为系统设计的原因，实际上log是全局唯一的，在系统初始化最初阶段，就已经从properties里面读取配置了（因为工厂类里面也会打印日志，如果这个时候不初始化日志系统，没法看到日志）。

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
麻烦能在develop分支试试问题解决了吗？
目前设计的策略是这样的：
1. 初始化阶段无法从用户或者配置文件读取日志存储路径时，会使用默认路径：
 homedir(~)/nacos/logs/nacos-sdk-cpp.log

2. 当用户第一次创建客户端对象时，允许用户通过properties文件或者properties属性初始化日志路径，但是只允许初始化一次

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
欢迎提供更好的解决方案和建议:)
