### ISSUE TITLE
static link to curl

### ISSUE THREAD

**Issue by swq123459** [nacos-group/nacos-sdk-cpp#65]
this sdk rely on curl， but no all linux-release have curl runtime
see https://curl.se/docs/install.html

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
Dear all nacos cpp client users,

If you have any problem compiling the client / link issues, please kindly inform me in this issue alone with the compile/platform/OS version information, I'll find a solution for you.

**Comment by swq123459** [comment]
```sh
$ cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)
$ gcc -v
gcc version 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC)
```

**Comment by swq123459** [comment]
If i want to use this client-sdk, i should link to libcurl, which no exist default in my system.I have to `yum install libcurl-devel`

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
I'll close this issue, but I'll keep it pinned so if there's anyone come across the same issue he can check this for help or ask for further help.
