### ISSUE TITLE
wstring error

### ISSUE THREAD

**Issue by yzz-ihep** [nacos-group/nacos-sdk-cpp#7]
error：
nacos-sdk-cpp/src/commons/ConstValue.cpp:5:46: 错误：请求从‘const char [12]’转换到非标量类型‘const wstring {aka const std::basic_string<wchar_t>}’ const std::wstring ConstValue::ClientName = "NacosClient";

I think wstring needs some function to be converted from char*，or just add “L” before your char*

**Comment by chaytanyasinha** [comment]
@yzz-ihep  Thanks for the issue.We will Check it out.

**Comment by yzz-ihep** [comment]
> @yzz-ihep Thanks for the issue.We will Check it out.

This error is in DEVELOPMENT branch，maybe it‘s not important

**Comment by chaytanyasinha** [comment]
@yzz-ihep okay. So you can check our master branch.
