### ISSUE TITLE
Missing Mutex.h "No such file or directory"

### ISSUE THREAD

**Issue by loadingvx** [nacos-group/nacos-sdk-cpp#71]
`
3rdparty/nacos-sdk-cpp/include/nacos-sdk/factory/NacosServiceFactory.h:9:10: fatal error: src/thread/Mutex.h: No such file or directory
    9 | #include "src/thread/Mutex.h"
`

no Mutex.h in `/install-dir/include/thread/`.

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
Could you provide the platform info(OS) and the compiler info? thanks!

**Comment by loadingvx** [comment]
ubuntu 20.04 Gcc 9.3.0, build with cmake3

```
wget https://github.com/nacos-group/nacos-sdk-cpp/archive/refs/tags/v1.0.7.tar.gz
tar -xzf  v1.0.7.tar.gz
cd nacos-sdk-cpp-1.0.7


#####  Manual Edit Makefile #####
LIBS = -lcurl -lpthread -lssl -lcrypto -lz
CCFLAGS = -g -Wall -O0 -fPIC -I$(shell pwd)/../../curl/include -L$(shell pwd)/../../curl/lib -I$(shell pwd)/../../openssl/include -L$(shell pwd)/../../openssl/lib -L$(shell pwd)/../../zlib/lib -I$(shell pwd)/../../zlib/include
##########################

make.  # OK!!
```

but~~ 
```
make DESTDIR=/tmp install
make: *** No rule to make target 'install'.  Stop.
```
 SO~ 

```

mkdir -p lib
mkdir -p include

cp -r nacos-sdk-cpp-1.0.7/include/* ./include/
cp -r nacos-sdk-cpp-1.0.7/libnacos-cli.* ./lib
```

Then~~

```
Missing Mutex.h "No such file or directory"
```

**Comment by loadingvx** [comment]
@TTTTTAAAAAKKKKEEEENNNN  an official  `make install` will be really nice, because I'm using `nacos-sdk-cpp` as a `3rdparty/lib` which mainly contains `lib/lib*.a` and `inlcude/*.h`;

but the released package has no `make install` support~ 

thanks~~

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
Thank you for your kind advice, I'm working on this.

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
Hi @loadingvx ,

I've adopted CMake to the project and adjusted the include dir.
You could try it on the master branch:
https://github.com/nacos-group/nacos-sdk-cpp

cmake .
make && make install
