### ISSUE TITLE
Not support access key and secret key

### ISSUE THREAD

**Issue by red-chen** [nacos-group/nacos-sdk-cpp#74]

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
Working on this, please wait.

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
Hi @red-chen 
Could you try this:
https://github.com/nacos-group/nacos-sdk-cpp/tree/develop

with the following configuration in your nacos-cpp-cli.properties (or property object):
```
accessKey=youraccesskey
secretKey=yoursecretkey
```
