### ISSUE TITLE
[FeatureRequest] When will selectOneHealthyInstance interface supported?

### ISSUE THREAD

**Issue by hiberabyss** [nacos-group/nacos-sdk-cpp#78]

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
Hi @hiberabyss 
You may refer to the test case 'testInstanceSelectors.cpp'
```C++
namingSvc->getInstanceWithPredicate("serviceName", &healthInstanceSelector);
```
You can also implement your own selectors to satisfy your specialized business requirement
