### ISSUE TITLE
nacos log

### ISSUE THREAD

**Issue by labman000** [nacos-group/nacos-sdk-cpp#84]
现在nacos的日志是每次启动的时候如果存在直接reflush该文件，如果服务重启了，之前的日志就没有了，能否改成追加的方式，并且后期能不能针对日志规划几个版本，做一个更加全面的日志系统呢？

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
你好 @labman000 ，
确实有这个问题，我们会增加针对这个的修复，使用追加的方式

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
你好 @labman000 ,

这个问题已经修复，并且合并到master分支：
https://github.com/nacos-group/nacos-sdk-cpp

谢谢你指出问题！
