### ISSUE TITLE
nacos-sdk-cpp 对json报文校验非法导致coredump

### ISSUE THREAD

**Issue by labman000** [nacos-group/nacos-sdk-cpp#85]
使用的过程中经常发现因为json报文的问题导致coredump，能优化下对应的json库吗，
例如启动时nacos密码输入错误时，会触发json解析异常，但是枚举值里是有nacos密码错误的，未校验的代码如下所示
![image](https://user-images.githubusercontent.com/67182735/127292825-90a762b0-23ef-4906-9b5c-c8bb5110c23a.png)

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
你好 @labman000 ，
请问能描述下具体的场景吗。
我的理解是当你服务器起来后，如果nacos-server修改了密码，这个客户端会crash 请问是这种情况吗？

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
你好 @labman000 ，

我分析了一下代码，再结合你说的情况。
发现目前的安全验证机制是这样的：
程序启动时会使用securityManager进行一次login以取得访问用的accessToken，后续会通过线程在后台刷新此token
1. 当启动程序时如果输入的用户名密码是错误的，程序会直接异常退出
2. 当后台线程刷新token发现密码不对，此时也会抛出异常退出

我的看法是情况1确实应该抛出异常 因为此时程序的设定就是错误的
情况2应该忽略这个错误，因为即使设定不对，程序中现有的数据还能保证其继续执行、或者程序拥有备用措施。
在这种情况下忽略异常，保证CAP中的A和P。

欢迎（任何看到这个issue的人）提出意见和讨论！

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
如果接下来一个月没有人对此有异议（2022年02月23日），将会按照此方案重新设计

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
你好 @labman000 ，

此问题已经于下述版本修复：
https://github.com/nacos-group/nacos-sdk-cpp/releases/tag/v1.1.0

This issue is fixed in the following release:
https://github.com/nacos-group/nacos-sdk-cpp/releases/tag/v1.1.0
