### ISSUE TITLE
Two Questions

### ISSUE THREAD

**Issue by yitian108** [nacos-group/nacos-sdk-cpp#87]
有两个问题想请教下：
（1）是否注册服务发现的代码需要与http服务器启动置于同一线程？貌似我分开后，有时会发生崩溃，之前未引入注册发现代码前没有崩溃。
（2）factory裸指针能否采用智能指针替代？
    NacosServiceFactory ***factory** = new NacosServiceFactory(props);
    ResourceGuard <NacosServiceFactory> _guardFactory(factory);
    ConfigService *n = factory->CreateConfigService();

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
你好 @yitian108 ，

麻烦能提供下crash的时候的corefile和日志吗，还有你在使用的编译器、操作系统信息，http服务器启动线程和注册服务是否在同一线程是没有要求的。

关于第二点，我们会进行优化。

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
你好 @yitian108，

关于第二点，可以直接使用智能指针替换掉这个ResourceGuard，不过系统将保留此特性以支持某些老的C98编译器
