### ISSUE TITLE
注册方法中使用namespaceid不能添加到对应命名空间中

### ISSUE THREAD

**Issue by JeremyJie** [nacos-group/nacos-sdk-cpp#88]
在instance结构体中添加namespaceid如何不能添加到对应命名空间中

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
你好 @JeremyJie ，
目前设计是通过Properties里面的NAMESPACE这个key在初始化的时候进行设定，之后都会在这个namespace中进行操作。
