### ISSUE TITLE
Who can help me to reuse the curl objects

### ISSUE THREAD

**Issue by TTTTTAAAAAKKKKEEEENNNN** [nacos-group/nacos-sdk-cpp#9]
If you check HTTPCli.cpp, you will find that on every http request, a new curl object is created and the old one is destroyed.
This is pretty weird, I know. You may possibly ask why I'm not using the same curl object -- that's because if I reuse it, I will get a 400 error and I don't know why
Could someone help me to reuse the curl object without 400 error?
thanks.

**Comment by yzz-ihep** [comment]
Which test case did you get the error? I change the code, add
`if(curlHandle != NULL)
                return curlHandle;`
and add  CURL *curlHandle in class HTTPCli, but i did not get an error.

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
> Which test case did you get the error? I change the code, add
> `if(curlHandle != NULL) return curlHandle;`
> and add CURL *curlHandle in class HTTPCli, but i did not get an error.

Problem is with the curlHandle's creation and release:
If you check the source code in HTTPCli.cpp:
[https://github.com/nacos-group/nacos-sdk-cpp/blob/master/src/http/HTTPCli.cpp](url) line 54
`CURL *HTTPCli::getCurlHandle()
{
	CURL *curlHandle = pthread_getspecific(pthreadKey);
	if (curlHandle == NULL)
	{
		curlHandle = curl_easy_init();
		pthread_setspecific(pthreadKey, reinterpret_cast<void*>(curlHandle));
	}
	else//TODO:Temporary solution for 400 response when performing multiple post request with one curl handle
	{
		curl_easy_cleanup(curlHandle);
		curlHandle = NULL;
		pthread_setspecific(pthreadKey, reinterpret_cast<void*>(curlHandle));
		return getCurlHandle();
	}//TODO:END:Temporary solution for 400 response when performing multiple post request with one curl handle

	return curlHandle;
}`

The curlHandle is created/destroyed on every request.
I'm finding a way to reuse the curlHandle in multiple requests (Currently, If you use the handle the second time, you will get an error with code 400)

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
Already resolved, please check code in dev branch, later I will create a release
