### ISSUE TITLE
通过cmake生成makefile时报错install TARGETS given no LIBRARY DESTINATION for shared library target   "nacos-cli".

### ISSUE THREAD

**Issue by sucaiji** [nacos-group/nacos-sdk-cpp#99]
具体报错内容如下：

CMake Error at CMakeLists.txt:57 (install):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "nacos-cli".

CMake Error at CMakeLists.txt:64 (install):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "nacos-cli".

-- Configuring incomplete, errors occurred!
See also "/root/nacos-sdk-cpp/CMakeFiles/CMakeOutput.log".
See also "/root/nacos-sdk-cpp/CMakeFiles/CMakeError.log".

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
你好 @sucaiji 
我已经修复cmakeList：
https://github.com/nacos-group/nacos-sdk-cpp

如果仍有问题，请继续联系我，谢谢！
